spring:

  datasource:
    password: ${DB_PASSWORD_17}
    username: ${DB_USERNAME_17}
    url: ${DB_URL_17}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true
    schemas:
      - s_auth

  logging:
    level:
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG
      com.practice.authservice: TRACE
      org.hibernate.SQL: DEBUG
      org.hibernate.type: TRACE

  kafka:
    bootstrap-servers: ${GOOGLE_SERVER}:9092

  servlet:
    multipart:
      enabled: true
      max-file-size: 150MB
      max-request-size: 150MB

jwt:
  secret-key: ${SECRET_KEY}
  access-token-expiration: 900000
  refresh-token-expiration: 2592000000

cookie:
  access-token-name: access-token
  refresh-token-name: refresh-token

file:
  upload-dir: ./uploads