spring:

  datasource:
    password: ${DB_PASSWORD_17}
    username: ${DB_USERNAME_17}
    url: ${DB_URL_17}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true
    schemas:
      - s_auth