spring:

  datasource:
    password: ${DB_PASSWORD_17}
    username: ${DB_USERNAME_17}
    url: ${DB_URL_17}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true
    schemas:
      - s_auth

  logging:
    level:
      org.springframework.security: TRACE

server:
  port: 8443
  ssl:
    enabled: true
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: mylocalcert

jwt:
  secret-key: ${SECRET_KEY}
  access-token-expiration: 900000
  refresh-token-expiration: 2592000000

cookie:
  access-token-name: __Secure-access-token
  refresh-token-name: __Secure-refresh-token